### ISSUE TITLE
我想说。。。。curl那个真的需要exe吗。。。

### ISSUE THREAD

**Issue by Artoria2e5** [RamseyX/RamseyX-client#3]
0 SorryForUsingChinese.IAmTooLazyToUseEnglish.
好了。。。。。我想说我一直以为只要那个include的几个文件就够了。。。。
然后makefile加个依赖什么的。。。

**Comment by Artoria2e5** [comment]
还有。。。。Qt那边关于OS和编译器是有特定的行为还是怎么了。。。。为什么会有unsupported这种事情啊。。。

**Comment by zizhengtai** [comment]
It is not enough to just include headers to link to libcurl. You need to link to the binary library, whether dynamically or statically. This version of RamseyX links dynamically to libcurl (note the -lcurldll in RamseyX.pro) in order to reduce the size of the executable file so that it will be easier to update the program later, so you need a libcurl.dll for the program to run. If you wish to link it statically, use the "LIBS += -L"directory of libcurl.a" -lcurl" and "-DCURL_STATICLIB" options in RamseyX.pro. Please note that it is best for you to build the latest version of libcurl from source if you wish to build RamseyX from source.

**Comment by zizhengtai** [comment]
It's not Qt, it's RamseyX. You can see in RamseyXHeader.h that I defined several macros to determine the OS and compiler being used. For now, I only have GCC and MSVC as options, for I haven't tested whether clang or other compilers will also work correctly for it. But please feel free to add some lines to the macros to make it work yourself.

**Comment by Artoria2e5** [comment]
got it
